USE [master]
GO

/****** Object:  Database [DbSinavOgrenci]    Script Date: 11.06.2023 17:18:17 ******/
CREATE DATABASE [DbSinavOgrenci]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DbSinavOgrenci', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DbSinavOgrenci.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DbSinavOgrenci_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DbSinavOgrenci_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DbSinavOgrenci].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DbSinavOgrenci] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET ARITHABORT OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DbSinavOgrenci] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DbSinavOgrenci] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DbSinavOgrenci] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DbSinavOgrenci] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET RECOVERY FULL 
GO

ALTER DATABASE [DbSinavOgrenci] SET  MULTI_USER 
GO

ALTER DATABASE [DbSinavOgrenci] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DbSinavOgrenci] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DbSinavOgrenci] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DbSinavOgrenci] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DbSinavOgrenci] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DbSinavOgrenci] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DbSinavOgrenci] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DbSinavOgrenci] SET  READ_WRITE 
GO

